apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
stringData:
  MONGODB_URI: mongodb://admin:admin123@mongodb-service:27017/chatApp?authSource=admin&retryWrites=true&w=majority
  JWT_SECRET: 0efe3eab844d6752c15706cc95070b24