apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mongodb-deployment 
  namespace: chatapp
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    
    spec:
      containers:
      - name: chatapp-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin 
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        # volumeMounts: 
        # - name: mongo-data
        #   mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc


