kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: chat-app
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storage-class
  hostPath:
    path: /data/mongodb