kind: Secret
apiVersion: v1
metadata:
  name: chatapp-secrets
  namespace: chat-app
data:
  jwt: ODQ2YmViM2VmOTc5MmVkZjBhNGExYTI3MmMyZjMxMDljNTc5Y2M2YmVkM2U2NzAzZDkwYjczYTlkMDg2NmVhNjA0ZTI1NTQyYjEyNTU1MTUwOGM5NDQ0MjVhNjc2ZGU3ZjNiYmVjOTZkZGViMmI1M2FjNzk0ZjdiMTFjYjNjOTk=